### ISSUE TITLE
挂了

### ISSUE THREAD

**Issue by StoneLeon** [seepine/spider-mzitu#1]
可能需要再加个iP代理池功能

**Comment by seepine** [comment]
改成了java版的，增加了代理池的配置，有兴趣的话可以重新clone试试，不增加线程和减少延时很稳定，跑好几个小时了

**Comment by seepine** [comment]
代理池找了许多免费的试验，都是报错，用自己多台云服务器测试，都没问题，几个代理就配几个线程仍然很稳
