### ISSUE TITLE
有bug，爬的图片比相册总是少一个，比如相册51个，只会爬取50个

### ISSUE THREAD

**Issue by ryanwlb** [seepine/spider-mzitu#2]

**Comment by ryanwlb** [comment]
我提交了下fix代码没推上来么？
int i = 2那行的问题

**Comment by seepine** [comment]
没有看到合并请求啊

**Comment by ryanwlb** [comment]
好吧第一次用github提交合并请求代码不太熟悉可能没提交上
还有两个问题想反馈下
1.有一些空白图也写在了cache里面，是不是后续就不会下载实际图片替换这个空白图了？
2.大佬能不能写一个动态获取代理IP之后动态更换的代码例子啊？
比如我有一个付费的代理获取IP链接
http://ip.11jsq.com/index.php/api/entry?method=proxyServer.generate_api_url&packid=3&fa=0&fetch_key=&groupid=0&qty=5&time=1&pro=&city=&port=1&format=txt&ss=1&css=&dt=1&specialTxt=3&specialJson=&usertype=16
返回txt格式的，怎么动态的把返回的IP使用上并且当IP出错的时候自动替换掉其他的IP

**Comment by seepine** [comment]
1.空白图的话理论上是的，解决办法就是把cache删掉重新跑，会检测图片是否下载，下载的是否为完整图片，所以重新跑跳过已下载正确的图片，会快得多也能把空白图片、缺的图片补上

**Comment by seepine** [comment]
2.获取代理ip的话我这边获取不到，所以我也没办法解析，不过思路也很简单，就是最开始的时候通过http请求接口获取数据，数据解析根据接口返回的数据将json转为object，再将代理ip转为数组替换现在的全局代理数组就可以了

**Comment by ryanwlb** [comment]
前面那部我已经实现了，上面我发的那个链接就是付费获取IP的链接，现在有两个地方不明白
第一就是您说的替换没太理解怎么实现？
第二每个IP可能5分钟就无法访问了，比如我同时用6个代理，此时要把这个IP单独去掉在重新获取一个补上这部怎么实现？
我这实现了一部分代码已经可以获取到IP并且解析成功，但是下一步不知道怎么做了，大佬可以帮忙完善下么？
//    private final static String GET_IP_URL = "http://t.11jsq.com/index.php/api/entry?method=proxyServer.generate_api_url&packid=3&fa=0&fetch_key=&groupid=0&qty=15&time=1&pro=&city=&port=1&format=json&ss=5&css=&dt=1&specialTxt=3&specialJson=&usertype=16";
//
//    public static Map<String, Integer> getIp() throws InterruptedException {
//        List<String> addrs = new LinkedList<String>();
//        Map<String, Integer> addr_map = new HashMap<String, Integer>();
//        Map<String, Integer> ipmap = new HashMap<String, Integer>();
//        ExecutorService exe = Executors.newFixedThreadPool(10);
//        for (int i = 0; i < 1; i++) {
//            Document doc = null;
//            try {
//                doc = Jsoup.connect(GET_IP_URL).get();
//            } catch (IOException e) {
//                continue;
//            }
//            System.out.println(doc.text());
//            JSONObject jsonObject = JSONObject.fromObject(doc.text());
//            List<Map<String, Object>> list = (List<Map<String, Object>>) jsonObject.get("data");
//            int count = list.size();
//
//            for (Map<String, Object> map : list) {
//                String ip = (String) map.get("IP");
//                Integer port = (Integer) map.get("Port");
//                ipmap.put(ip, port);
//            }
//            exe.shutdown();
//            Thread.sleep(1000);
//        }
//        return ipmap;
//    }

**Comment by ryanwlb** [comment]
同一组相同有效时长的IP也有可能有的时间用的久有的用的短，所以不知怎么动态替换无法使用的

**Comment by seepine** [comment]
可以看downloader.MyHttpClientDownloader.java

**Comment by ryanwlb** [comment]
那要怎么捕获到哪个IP出异常了替换掉呢？

**Comment by ryanwlb** [comment]
说实话太菜了没太看懂，大佬能不能帮忙处理下，我可以把我买的代理IP共享

**Comment by seepine** [comment]
这个看你是否紧急，我这边得业余时间才能处理

**Comment by ryanwlb** [comment]
不紧急，大佬有时间处理下就行，大佬留一下邮箱吧，我把买的代理IP链接发给你

**Comment by seepine** [comment]
seepine@163.com

**Comment by ryanwlb** [comment]
已发送，每个IP有效期25分钟到3小时，有效时间到明天这个时候

**Comment by ryanwlb** [comment]
有一些白图怎么是269字节有一些是0字节？是不是269字节的白图不会被替换了？

**Comment by seepine** [comment]
1.昨天代理池那个接口，有ip限制我这边访问不到数据

**Comment by seepine** [comment]
2.图片下一半大小非0的也会被替换，因为判断不是使用文件大小来判断，而是判断文件是不是一个有效图片，可看`util/FIleUtil.java`
```
public boolean isValidImage(final String filePath) {
        try {
            ImgUtil.read(filePath).getAccelerationPriority();
            return true;
        } catch (Exception e) {
            return false;
        }
    }
```

**Comment by ryanwlb** [comment]
你加一下我vx971223003  你调用的时候我现充值之后把你IP加到白名单里面去

**Comment by ryanwlb** [comment]
或者你去http://www.zhilianhttp.com/Index/getapi.html这个网站  注册之后每天可以免费领取10个IP

**Comment by ryanwlb** [comment]
或者我怎么把钱转给你你充值，请大佬有时间一定要实现下动态切换代理，很好奇怎么实现，谢谢大佬了

**Comment by seepine** [comment]
不好意思，最近都会比较忙没有时间搞，我看了一下ip充值，你是哪一种，知道固定时间呢，还是不知道而是随机时间的，另外你帮我实验一下，过期是怎么个过期法，比如api获取到10个，一定时间后有5个过期，`api再去获取会只获取到5个`，或者`获取到还是原来的10个包含过期的5个`，还是`获取到10个但是过期的替换成有效的了`
![image](https://user-images.githubusercontent.com/52092701/85964850-9536b680-b9ed-11ea-97a8-41a0c4697247.png)

**Comment by ryanwlb** [comment]
使用IP分为两种（我建议使用第二种参数方式设置，比较便宜）：
1.充值代理币，没有到期时间限制，提取时候按照每个IP扣费，IP到期时间为提取时候选择的有效期（比如5-25分钟）
2.按天充值，每天提取固定IP，这种知道固定时间范围，比如1-5分钟，5-25分钟，25分钟-3小时，比如选择购买5-25分钟的IP，数量100个，账号有效期一天，在一天内我可以使用100个IP，假设每个IP可以使用时间为5-25分钟，（生成api链接时候可以自己设置很多参数，包括这个提取数量等等，比如设置10个，下次再调用这个api会返回和之前完全不同的10个新ip），比如第一次我提取了10个，有效期5-25分钟，使用了5个，这时候我可用IP数量为95个，从提取那一刻计算过了最多25分钟剩下的5个也无法使用了但是不会扣费（不会让你一直占用会释放会池子里），下次我在提取10个会重新返回10个有效的IP（不包含失效的5个也不包含已使用的5个，如果账号可用不足10个会返回可用的数量），提取不收费，使用才开始收费，但是有效期从提取就开始计算了。即使不使用也会过期但不会扣费。

**Comment by ryanwlb** [comment]
使用IP分为两种
1.充值代理币，没有到期时间限制，提取时候按照每个IP扣费，IP到期时间为提取时候选择的有效期
2.按天充值，每天提取固定IP

我建议第二种比较可控提取固定时间的，比如15分钟

比如选择购买15分钟的IP，数量100个，假设每个IP可以使用时间为15分钟，比如第一次我提取了10个，有效期15分钟，在这15分钟内使用了5个，这时候我可用IP数量为95个，剩下的5个会过期释放到池子里，下次重新提取在提取10个会重新返回10个有效的IP（不包含已使用的5个也不包含过期的5个，因为在生成api时候有个参数是默认当日去重自动选中的），提取不收费，使用才开始收费，但是有效期从提取就开始计算了。即使不使用也会过期但不会扣费。

**Comment by ryanwlb** [comment]
其实现在有两种情况需要更换IP，一种是IP到期了无法使用，另一种是网站反爬，比如提取的IP是15分钟，在这15分钟内如果没有被反爬一切ok15分钟后替换一批新的就ok了，但是如果在这15分钟内有部分IP被反爬了会抛出一个异常，这个异常信息带有被反爬了的IP，不知道是否可以去捕获这个失效的IP动态剔除更换成新IP？

**Comment by ryanwlb** [comment]
大佬在测试的时候可以选择用每日免费赠送的IP也可以用我账号的IP（不知换机器登录是否需要验证码，如果需要的话我看到了会来这留言）
账号：jcccccccc  密码:zhangaaa，登录时候需要点击我的用户名在左侧菜单里面加入IP白名单， 账号里面还有10块钱的代理币，可以提取330个15分钟的ip。

**Comment by ryanwlb** [comment]
求大佬有时间维护下代理池

**Comment by seepine** [comment]
不好意思前段时间比较忙,代理池部分改好了,经测试也可以使用,时间仓库代码及各方面处理不是很优雅,不过是不影响功能的,你可以拉最新代码测试一下

使用方法:
生成api地址
![image](https://user-images.githubusercontent.com/52092701/89405576-629b7e80-d74e-11ea-9d7d-9d4dd318ee79.png)
放到项目中
![image](https://user-images.githubusercontent.com/52092701/89405636-7ba42f80-d74e-11ea-9938-dee395fd1bcd.png)
配置自动获取开关we为true
![image](https://user-images.githubusercontent.com/52092701/89405903-e81f2e80-d74e-11ea-8f42-cad1fdfa5678.png)

最后放开爬取线程数和下载线程数即可,线程数可根据你一次提取10个代理地址,线程数就配置10

**Comment by seepine** [comment]
昨天已更新


| |
seepine
|
|
seepine@163.com
|
签名由网易邮箱大师定制
在2020年7月18日 22:17，Ryan WLB<notifications@github.com> 写道：

求大佬有时间维护下代理池

**Comment by ryanwlb** [comment]
感谢大佬

**Comment by ryanwlb** [comment]
试了一下太NB了，万分感谢大佬，顺便问一下这个是需要一次多提取一些还是一次可以少提取过期了会自动用了链接重新提取？以及如果判断一个ip是否到了时间呢？看到了有R这个类用这个类的code去判断但是没太看懂getCode  0是怎么得到的？

**Comment by seepine** [comment]
因为这个代理网的规则提取不扣钱，使用扣钱，建议最好是你想开10个线程，你就一次提取10个ip
过期会自动重新提取，因为我接口是选1分钟有效，所以直接写死59秒自动获取新的，你要修改的话可以看
![image](https://user-images.githubusercontent.com/52092701/89753336-74906f00-db0a-11ea-853c-33fdd8aeca80.png)
要判断ip是否到期也不难，接口勾选上返回过期时间，ProxyData实体类加上过期时间的字段，获取到这样就能拿到每个代理的过期时间，然后每个代理再启动一个定时器时间到自动剔除再拿新的就行

**Comment by ryanwlb** [comment]
谢谢大佬
